### ISSUE TITLE
In README, how to help just give the cURL call

### ISSUE THREAD

**Issue by DAE51D** [disforw/goveelife#23]
For many folks setting up something like [Postman ](https://www.postman.com/) or whatever to do the API call may be overkill... I'm pretty sure all Mac OSX, Linux and Windows 11 come with `cURL` installed by default...

So in your https://github.com/disforw/goveelife?tab=readme-ov-file#how-can-you-help section, maybe just paste this in there

```bash
curl -H 'Govee-API-Key: YOURKEYHERE' -o 'Govee API response.json' -X GET https://openapi.api.govee.com/router/api/v1/user/devices
```

**Comment by disforw** [comment]
added

**Comment by DAE51D** [comment]
I do see it at the bottom, but to make it more clear, maybe use the markdown tags like ``` to make a code block around it?
