### ISSUE TITLE
Dual outlet API GET response

### ISSUE THREAD

**Issue by ngholson** [disforw/goveelife#4]
{
  "code": 200,
  "message": "success",
  "data": [
    {
      "sku": "H5082",
      "device": "E1:EE:60:74:XX:XX:XX:XX:XX",
      "deviceName": "garage lights",
      "type": "devices.types.socket",
      "capabilities": [
        {
          "type": "devices.capabilities.on_off",
          "instance": "powerSwitch",
          "parameters": {
            "dataType": "ENUM",
            "options": [
              {
                "name": "on",
                "value": 1
              },
              {
                "name": "off",
                "value": 0
              }
            ]
          }
        }
      ]
    },
    {
      "sku": "H5082",
      "device": "42:C9:60:74:XX:XX:XX:XX:XA",
      "deviceName": "Garage Outlets",
      "type": "devices.types.socket",
      "capabilities": [
        {
          "type": "devices.capabilities.on_off",
          "instance": "powerSwitch",
          "parameters": {
            "dataType": "ENUM",
            "options": [
              {
                "name": "on",
                "value": 1
              },
              {
                "name": "off",
                "value": 0
              }
            ]
          }
        }
      ]
    },
    {
      "sku": "H5082",
      "device": "2E:F3:60:74:XX:XX:XX:XX:XC",
      "deviceName": "controlDev",
      "type": "devices.types.socket",
      "capabilities": [
        {
          "type": "devices.capabilities.on_off",
          "instance": "powerSwitch",
          "parameters": {
            "dataType": "ENUM",
            "options": [
              {
                "name": "on",
                "value": 1
              },
              {
                "name": "off",
                "value": 0
              }
            ]
          }
        }
      ]
    }
  ]
}

**Comment by disforw** [comment]
How many devices do you have? Is this 3 separate devices? Or just one?

**Comment by disforw** [comment]
According to this response, you should already have 3 devices, each with a single on/off switch.

**Comment by ngholson** [comment]
6 total controllable outlets. Each device has 2 independent outlets or the
entire block can be turned off.

**Comment by ngholson** [comment]
I am thinking that this may be a shortcoming on the govee api, it doesn't
appear that allows for both outlets to be controlled separately via the API

**Comment by disforw** [comment]
Yeah, if this is 3 separate physical units, then the API is only offering a single switch per unit.

**Comment by disforw** [comment]
Closing as limited API, hope they improve, but until then…
